installed_at: '2026-01-30T19:35:12+00:00'
skill_id: christopheryeo/claude-skills/new-presentation
git_repo: https://github.com/christopheryeo/claude-skills.git
skill_path: /main/new-presentation
git_sha: 5c4bb12285b5c9bc3d8fa8e05aa976830b5baace
skilz_version: 1.10.0
install_mode: copy
canonical_path: null
